# Generated by Django 2.1.3 on 2019-11-10 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Eprint_users', '0016_profile_has_high_prt'),
    ]

    operations = [
        migrations.AddField(
            model_name='printdocs',
            name='AC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printdocs',
            name='dest_point',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='printdocs',
            name='seats_vac',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='printdocs',
            name='source_point',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='printdocs',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
