# Generated by Django 2.1.3 on 2019-11-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eprint_users', '0018_auto_20191111_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_point', models.CharField(default='', max_length=25)),
                ('dest_point', models.CharField(default='', max_length=25)),
                ('AC', models.BooleanField(default=False)),
                ('seats_vac', models.IntegerField(default=1)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'HostSearch',
            },
        ),
        migrations.RemoveField(
            model_name='printdocs',
            name='AC',
        ),
        migrations.RemoveField(
            model_name='printdocs',
            name='dest_point',
        ),
        migrations.RemoveField(
            model_name='printdocs',
            name='seats_vac',
        ),
        migrations.RemoveField(
            model_name='printdocs',
            name='source_point',
        ),
        migrations.RemoveField(
            model_name='printdocs',
            name='start_time',
        ),
    ]
