# Generated by Django 2.1.3 on 2019-11-10 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eprint_users', '0020_hostsearch_task_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='custsearch',
            name='request_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Eprint_users.HostSearch'),
        ),
    ]
