# Generated by Django 2.1.3 on 2019-11-15 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eprint_users', '0022_custsearch_task_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custsearch',
            name='request_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Eprint_users.HostSearch'),
        ),
    ]
