# Generated by Django 2.1.3 on 2019-11-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eprint_users', '0023_auto_20191116_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='custsearch',
            name='host_accept',
            field=models.BooleanField(default=False),
        ),
    ]
