# Generated by Django 2.1.3 on 2019-11-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eprint_users', '0024_custsearch_host_accept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='amount_due',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='has_high_prt',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_faculty',
        ),
        migrations.AddField(
            model_name='profile',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
        ),
    ]
