# Generated by Django 2.1.3 on 2019-11-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eprint_users', '0025_auto_20191116_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='custsearch',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
