# Generated by Django 2.1.3 on 2019-11-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eprint_users', '0026_custsearch_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hash_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=3),
        ),
    ]
