# Generated by Django 2.1.3 on 2019-11-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eprint_users', '0027_auto_20191116_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostsearch',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
