# Generated by Django 2.1.3 on 2019-11-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eprint_users', '0028_hostsearch_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='custsearch',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='custsearch',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='hostsearch',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='hostsearch',
            name='rating1',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='hostsearch',
            name='rating2',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=3),
        ),
    ]
